### ISSUE TITLE
Room  attempt to re-open an already-closed object: SQLiteDatabase

### ISSUE THREAD

**Issue by daimonkor** [googlesamples/android-architecture-components#276]
I have simple Singleton Database and miration_1_2, so it is simple, likely example, but when I call
```
Database.getInstance(context)
Database.getInstance(context)

or

Database.getInstance(this).feedDao().getAllFeed()
.flatMap({ url -> Database.getInstance(this).feedDao().getItem(url)})
```

I see error message
` java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase`
I know problem is with calling onMigrate twice. How I can add onUpgrade callback? How fix? Thanks for support.

**Comment by iammert** [comment]
Did you change schema again after migration? Probably you need to give new migration information to Room. If not, can you paste your full stacktrace here?

**Comment by daimonkor** [comment]
```
@Database(entities = [Feed::class, NewsWidget::class, NewsWidgetFeed::class], version = 2)
abstract class Database : RoomDatabase() {

    abstract fun feedDao(): FeedDao
    abstract fun newsWidgetDao(): NewsWidgetDao
    abstract fun newsWidgetFeedDao(): NewsWidgetFeedDao

    companion object {

        @Volatile private var INSTANCE: com.icebergteam.cryptocoinassistant.data.room.Database? = null

        fun getInstance(context: Context): com.icebergteam.cryptocoinassistant.data.room.Database =
                INSTANCE ?: synchronized(this) {
                    INSTANCE ?: buildDatabase(context).also { INSTANCE = it }
                }

        private val IO_EXECUTOR = Executors.newSingleThreadExecutor()

        /**
         * Utility method to run blocks on a dedicated background thread, used for io/database work.
         */
        fun ioThread(f: () -> Unit) {
            IO_EXECUTOR.execute(f)
        }

        private fun buildDatabase(context: Context) =
                Room.databaseBuilder(context.applicationContext,
                        com.icebergteam.cryptocoinassistant.data.room.Database::class.java, "settings.db")
                        .addMigrations(MIGRATION_1_2)
                        .fallbackToDestructiveMigration()
                        .addCallback(object : RoomDatabase.Callback() {
                            override fun onOpen(db: SupportSQLiteDatabase) {
                                LogManager.LogEA(db.version)
                                super.onOpen(db)

                            }

                            override fun onCreate(db: SupportSQLiteDatabase) {
                                super.onCreate(db)
                                ioThread {
                                    getInstance(context).feedDao().insert(*INIT_FEED_TABLE)
                                }
                            }
                        })
                        .build()

        val MIGRATION_1_2: Migration = object: Migration(1, 2) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE NewsWidget ADD COLUMN interval_anim INTEGER DEFAULT 6000")
            }
        }

        val INIT_FEED_TABLE = arrayOf(
                Feed("https://censor.net.ua/includes/resonance_ru.xml"),
                Feed("https://geektimes.ru/rss/interesting/"),
                Feed("http://k.img.com.ua/rss/ru/companies.xml"))
    }
}`

http://prntscr.com/hxjsm5
NewsRepositoryImpl is repository, using Singleton Database for select and insert transactions

**Comment by florina-muntenescu** [comment]
The migration failed because you're missing indices - this is what the 2nd error says in the ` Migration didn't properly handle newswidget` error message.

**Comment by daimonkor** [comment]
@florina-muntenescu 
Sorry, my fail, please look current
```
01-09 20:03:20.801 9784-9812/? E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
                                                 Process: com.icebergteam.cryptocoinassistant, PID: 9784
                                                 java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/com.icebergteam.cryptocoinassistant/databases/settings.db
                                                     at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
                                                     at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1659)
                                                     at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
                                                     at android.arch.persistence.db.framework.FrameworkSQLiteDatabase.execSQL(FrameworkSQLiteDatabase.java:240)
                                                     at com.icebergteam.cryptocoinassistant.data.room.Database$Companion$MIGRATION_1_2$1.migrate(Database.kt:60)
                                                     at android.arch.persistence.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:73)
                                                     at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:118)
                                                     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
                                                     at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                                                     at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:93)
                                                     at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:54)
                                                     at android.arch.persistence.room.RoomDatabase.inTransaction(RoomDatabase.java:305)
                                                     at android.arch.persistence.room.InvalidationTracker$1.run(InvalidationTracker.java:281)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                     at java.lang.Thread.run(Thread.java:818)
```

**Comment by hujiating** [comment]
I meet this problem too , have you resolved it?

**Comment by MedveDomg** [comment]
plus one

**Comment by daimonkor** [comment]
I see problem with init db and migration. There are asynchronius processes, so first  calling 
Database.getInstance(this).feedDao().getAllFeed() got empty list. How can I create init and migration processes as synchronius or maybe call init db before calling Database.getInstance(this).feedDao().getAllFeed()?

**Comment by easyandroid** [comment]
+1

**Comment by BartNijland91** [comment]
+1

**Comment by kostya17** [comment]
+1

**Comment by drayan85** [comment]
+1

**Comment by drayan85** [comment]
@kostya17 , @BartNijland91 , @easyandroid , @daimonkor , @florina-muntenescu , @iammert 

I have Managed to find the issue.

In my SQLiteHelper (older version) one column for `Long` Primitive Type
```
created_at=Column{name='created_at', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=0}
```

In the Room Entity Class, I have define the primitive type as follows **`private Long created_at`** which created as follows ( Not Null):
```
created_at=Column{name='created_at', type='INTEGER', affinity='3', notNull=false, primaryKeyPosition=0}
```

For Example If the RoomDatabase Extended Class Name **`AppDatabase.Java`** after the build, There will be a class Call **`AppDatabase_Impl.java`**

By debugging the `AppDatabase_Impl.Java` generated class we can find which Table Migration is failed.

```java
        final HashMap<String, TableInfo.Column> _columnsTblTrackerEvent = new HashMap<String, TableInfo.Column>(6);
        _columnsTblTrackerEvent.put("_id", new TableInfo.Column("_id", "INTEGER", true, 1));
        _columnsTblTrackerEvent.put("created_at", new TableInfo.Column("created_at", "INTEGER", false, 0));
        _columnsTblTrackerEvent.put("activity_type", new TableInfo.Column("activity_type", "TEXT", false, 0));
        _columnsTblTrackerEvent.put("country", new TableInfo.Column("country", "TEXT", false, 0));
        _columnsTblTrackerEvent.put("params_object", new TableInfo.Column("params_object", "TEXT", false, 0));
        final HashSet<TableInfo.ForeignKey> _foreignKeysTblTrackerEvent = new HashSet<TableInfo.ForeignKey>(0);
        final HashSet<TableInfo.Index> _indicesTblTrackerEvent = new HashSet<TableInfo.Index>(1);
        _indicesTblTrackerEvent.add(new TableInfo.Index("index_tbl_tracker_event__id", true, Arrays.asList("_id")));
        final TableInfo _infoTblTrackerEvent = new TableInfo("tbl_tracker_event", _columnsTblTrackerEvent, _foreignKeysTblTrackerEvent, _indicesTblTrackerEvent);
        final TableInfo _existingTblTrackerEvent = TableInfo.read(_db, "tbl_tracker_event");

       /** **Below If Condition is failed and Throws IllegalStateException** */
        if (! _infoTblTrackerEvent.equals(_existingTblTrackerEvent)) {
          throw new IllegalStateException("Migration didn't properly handle tbl_tracker_event(com.room.sample.TrackerEventLog).\n"
                  + " Expected:\n" + _infoTblTrackerEvent + "\n"
                  + " Found:\n" + _existingTblTrackerEvent);
        }
```

But when run the app, it crash and throwing IllegalState Exception but the error message

**`java.lang.IllegalStateException: attempt to re-open an already-closed object`**

Instead of ::

**`"Migration didn't properly handle tbl_tracker_event(com.room.sample.TrackerEventLog).\n"
                  + " Expected:\n" + _infoTblTrackerEvent + "\n"
                  + " Found:\n" + _existingTblTrackerEvent`**
