### ISSUE TITLE
WorkManagerSample: NullPointerException in androidx.work library itself

### ISSUE THREAD

**Issue by brainail** [googlesamples/android-architecture-components#356]
```java
 FATAL EXCEPTION: pool-1-thread-1
    Process: com.example.background, PID: 6387
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.work.State.isFinished()' on a null object reference
        at androidx.work.impl.WorkerWrapper.tryCheckForInterruptionAndNotify(WorkerWrapper.java:192)
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:146)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Steps to reproduce**: To reproduce just tap **GO/STOP** quickly three or more times. 

**Reproduced**: Always

**Comment by tikurahul** [comment]
Fixed. 

https://developer.android.com/jetpack/docs/release-notes#may_24_2018
