### ISSUE TITLE
[QUESTION] Proguard rules?

### ISSUE THREAD

**Issue by daimonkor** [googlesamples/android-architecture-components#37]
What kind of rules are needed for proguard?
`Caused by: java.lang.RuntimeException: Cannot create an instance of class ***.login.k
                                                       at android.arch.lifecycle.n$a.a(Unknown Source)
                                                       at android.arch.lifecycle.m.a(Unknown Source)
                                                       at android.arch.lifecycle.m.a(Unknown Source)
                                                       at ***.LoginActivity.onCreate(Unknown Source)`
Thanks for help.

**Comment by amaksoft** [comment]
Hi, I've already created an [issue](https://issuetracker.google.com/issues/62113696) for providing proguard config. I haven't figured out all the necessary rules for livedata and room yet, but Lifecycle and ViewModel compile and seem to work fine.
Please try the provided rules and report any of your problems there, so that we could document and solve them.

**Comment by daimonkor** [comment]
Great work, thanks.

**Comment by daimonkor** [comment]
Great work, thanks.
