### ISSUE TITLE
NavigationBasicSample Build Error

### ISSUE THREAD

**Issue by firatkarababa** [googlesamples/android-architecture-components#383]
When I try to build NavigationBasicSample, I get the following error.

Caused by: org.gradle.api.tasks.StopExecutionException: Configuration on demand is not supported by the current version of the Android Gradle plugin since you are using Gradle version 4.6 or above. Suggestion: disable configuration on demand by setting org.gradle.configureondemand=false in your gradle.properties file or use a Gradle version less than 4.6.
	at com.android.build.gradle.BasePlugin.checkConfigureOnDemandGradleVersionCompat(BasePlugin.java:898)
	at com.android.build.gradle.BasePlugin.apply(BasePlugin.java:259)
	at com.android.build.gradle.AppPlugin.apply(AppPlugin.java:120)
	at com.android.build.gradle.AppPlugin.apply(AppPlugin.java:47)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
	at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:164)
	at org.gradle.api.internal.plugins.DefaultPluginManager.access$200(DefaultPluginManager.java:47)
	at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:252)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
	... 121 more

**Comment by artnest** [comment]
![image](https://user-images.githubusercontent.com/16272113/40960964-ec6646ce-68a9-11e8-8824-7352617feb8e.png)
You need to check your Android Studio settings for the project and uncheck "Configure on demand" option.

**Comment by firatkarababa** [comment]
I have sent a PR to solve this error. It seems to be caused by Android Gradle Plugin version.

**Comment by ianhanniballake** [comment]
We've since updated to Android Gradle Plugin 3.3.0.
