### ISSUE TITLE
NavigationBasicSample crash when `navigate` after `popupTo`

### ISSUE THREAD

**Issue by thaihuynhxyz** [googlesamples/android-architecture-components#435]
I build NavigationBasicSample on Pixel XL 2 emulator API 28.

Step1: Match navigate action_match_to_in_game
Step2: InGame navigate action_in_game_to_gameOver 
Step3: Back press to Match
Step4: Match navigate action_match_to_in_game crash

Note: if in Step3 we press [Try Again?] to use popupTo, the app has no crash.

```
08-02 11:34:53.842 2885-2885/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.navigationsample, PID: 2885
    java.lang.IllegalArgumentException: navigation destination com.example.android.navigationsample:id/action_match_to_in_game is unknown to this NavController
        at androidx.navigation.NavController.navigate(NavController.java:669)
        at androidx.navigation.NavController.navigate(NavController.java:628)
        at androidx.navigation.NavController.navigate(NavController.java:616)
        at com.example.android.navigationsample.Match$onCreateView$1.onClick(Match.kt:36)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by enekonieto** [comment]
I had similar problem with my own code. It was caused by version 1.0.0-alpha04 of Navigation component, it was fixed when using 1.0.0-alpha03.

**Comment by JakeSteam** [comment]
Note that 1.0.0-alpha05 is out now, so upgrade to that instead of downgrading!

**Comment by enekonieto** [comment]
Bug is gone with alpha05, thank you developers!

**Comment by thaihuynhxyz** [comment]
Yeah, not crashed anymore on alpha05. Thank you developers!

**Comment by gilgoldzweig** [comment]
bug returns on 1.0.0-alpha06 ktx

java.lang.IllegalArgumentException: navigation destination com.nyx.tech.dev:id/action_home_fragment_to_calibration_fragment is unknown to this NavController
        at androidx.navigation.NavController.navigate(NavController.java:691)
        at androidx.navigation.NavController.navigate(NavController.java:648)
        at androidx.navigation.NavController.navigate(NavController.java:634)
        at androidx.navigation.NavController.navigate(NavController.java:712)
        at com.nyx.tech.fragments.home.HomeFragment.onFeatureInitiated(HomeFragment.kt:240)
        at com.nyx.tech.fragments.home.HomeFragmentPresenter$observe$1.onChanged(HomeFragmentPresenter.kt:177)
        at com.nyx.tech.fragments.home.HomeFragmentPresenter$observe$1.onChanged(HomeFragmentPresenter.kt:50)
        at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
        at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
        at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
        at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at android.arch.lifecycle.LiveData$1.run(LiveData.java:87)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-14 15:23:52.527 23366-23427/com.nyx.tech.dev W/NYXApplication$onCreate: com

**Comment by JakeSteam** [comment]
@gilgoldzweig suggest you raise it on https://github.com/googlesamples/android-architecture-components/issues/446 instead, since this ticket is closed.

**Comment by dennisrufigill** [comment]
Even I was facing this same issue, then I changed (1.0.0-alpha04) to (1.0.0-alpha03) and it was resolved.
Thanks for the help :)

**Comment by fshdn1221** [comment]
It reproduce again in `2.3.0-alpha04` navigate crash after i clear backstack by call `popUpTo` with global actions

` <action
        android:id="@+id/clear"
        app:launchSingleTop="true"
        app:popUpTo="@id/nav_graph_home"
        app:popUpToInclusive="true" />`

**Comment by douhaogege** [comment]
my app 2.2.1, had the bug,please 
how resolved

**Comment by BitMobix** [comment]
I,m fixed bug.
Problem DONT UI thread...

This is working 
```
activity?.runOnUiThread{
                        findNavController().popBackStack()
                    }
```

**Comment by merwanezio** [comment]
using 2.3.0 with the same Problem , is this a bug or are we doing something wrong ? 
runOnUiThread didnt work for me

**Comment by khangdm** [comment]
> activity?.runOnUiThread{
>                         findNavController().popBackStack()
>                     }

i using lasted version but not work for me

**Comment by merwanezio** [comment]
https://stackoverflow.com/questions/63979643/random-crashes-when-using-androidx-navigation/65080641#65080641
