### ISSUE TITLE
WorkWrapper.java fatal exception.

### ISSUE THREAD

**Issue by core2root** [googlesamples/android-architecture-components#493]
Had my app crashed because of this Exception.
I'm using work manager version : 1.0.0-alpha08

Fatal Exception: android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 266)
       at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:845)
       at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
       at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:145)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:134)
       at androidx.work.impl.model.WorkTagDao_Impl.getTagsForWorkSpecId(WorkTagDao_Impl.java:92)
       at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:114)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

**Comment by ianhanniballake** [comment]
Please file issues with WorkManager on the [issue tracker](https://issuetracker.google.com/issues/new?component=409906) with a sample project that reproduces your issue.
