### ISSUE TITLE
Could anyone explain using AutoClearedValue ?

### ISSUE THREAD

**Issue by AlexFrost** [googlesamples/android-architecture-components#69]
I try to understand why here 
https://github.com/googlesamples/android-architecture-components/blob/master/GithubBrowserSample/app/src/main/java/com/android/example/github/ui/repo/RepoFragment.java

need to use 

```
    AutoClearedValue<RepoFragmentBinding> binding;
    AutoClearedValue<ContributorAdapter> adapter;
```
I can understand why memory lick is here https://github.com/googlesamples/android-architecture-components/issues/16 ObservableField product from ProductViewModel has link to activity.

But I spend a lot of time to find how RepoViewModel can hold link to fragment and why we should use AutoClearedValue 

Thanks.

**Comment by yigit** [comment]
RepoViewModel never holds a link to the Fragment outside the lifecycle scope, which are automatically cleared.
`AutoClearedValue` is instead used to allow garbage collection of fragment views.

**Comment by AlexFrost** [comment]
Thanks for the answer

**Comment by degea9** [comment]
I read the old source code of AutoClearedValue written in Java and I agree with @yigit about "AutoClearedValue is instead used to allow garbage collection of fragment views."
```
public AutoClearedValue(Fragment fragment, T value) {
        FragmentManager fragmentManager = fragment.getFragmentManager();
        fragmentManager.registerFragmentLifecycleCallbacks(
                new FragmentManager.FragmentLifecycleCallbacks() {
                    @Override
                    public void onFragmentViewDestroyed(FragmentManager fm, Fragment f) {
                        if(fragment == f) {
                            AutoClearedValue.this.value = null;
                            fragmentManager.unregisterFragmentLifecycleCallbacks(this);
                        }
                    }
                },false);
        this.value = value;
    }

```
as we observe onFragmentViewDestroyed ,then clear the value.
But in the newer version(AutoClearedValue.kt),AutoClearedValue will only observe fragment'lifecycle NOT the lifecycle of fragment's view.
```
init {
        fragment.lifecycle.addObserver(object : LifecycleObserver {
            @OnLifecycleEvent(Lifecycle.Event.ON_DESTROY)
            fun onDestroy() {
                _value = null
            }
        })
    }
```

Will it leak the fragment's view when fragment is added To BackStack(onDestroyView is called but the fragment's instance is NOT destroyed) ?

**Comment by azizbekian** [comment]
@yigit, would really appreciate if you can find time to answer @degea9's questions. I'm experiencing crashes on production because `getValue()` results in throwing an exception. Cannot reproduce.

Here's stacktrace:


> Fatal Exception: java.lang.IllegalStateException: should never call auto-cleared-value get when it might not be available
       at com.example.common.AutoClearedValue.getValue + 28(AutoClearedValue.java:28)
       at com.example.base.fragment.BindingFragment.getBinding(BindingFragment.java:7)
       at com.example.base.fragment.BindingFragment.setBinding(BindingFragment.java:5)
       at com.example.base.fragment.BindingFragment.onViewCreated + 28(BindingFragment.java:28)
       at androidx.fragment.app.FragmentManagerImpl.moveToState + 891(FragmentManagerImpl.java:891)
       at androidx.fragment.app.FragmentManagerImpl.addAddedFragments + 2096(FragmentManagerImpl.java:2096)
       at androidx.fragment.app.FragmentManagerImpl.transitToStyleIndex(FragmentManagerImpl.java:62)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether + 1870(FragmentManagerImpl.java:1870)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute + 1826(FragmentManagerImpl.java:1826)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions + 1726(FragmentManagerImpl.java:1726)
       at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange + 2659(FragmentManagerImpl.java:2659)
       at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated + 2609(FragmentManagerImpl.java:2609)
       at androidx.fragment.app.Fragment.performActivityCreated + 2619(Fragment.java:2619)
       at androidx.fragment.app.FragmentManagerImpl.moveToState + 903(FragmentManagerImpl.java:903)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState + 1237(FragmentManagerImpl.java:1237)
       at androidx.fragment.app.FragmentManagerImpl.moveToState + 1302(FragmentManagerImpl.java:1302)
       at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange + 2655(FragmentManagerImpl.java:2655)
       at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated + 2609(FragmentManagerImpl.java:2609)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated + 246(FragmentController.java:246)
       at androidx.fragment.app.FragmentActivity.onStart + 542(FragmentActivity.java:542)
       at androidx.appcompat.app.AppCompatActivity.onStart + 201(AppCompatActivity.java:201)
       at android.app.Instrumentation.callActivityOnStart + 1391(Instrumentation.java:1391)
       at android.app.Activity.performStart + 7347(Activity.java:7347)
       at android.app.ActivityThread.handleStartActivity + 3110(ActivityThread.java:3110)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence + 180(TransactionExecutor.java:180)
       at android.app.servertransaction.TransactionExecutor.cycleToPath + 165(TransactionExecutor.java:165)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState + 142(TransactionExecutor.java:142)
       at android.app.servertransaction.TransactionExecutor.execute + 70(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage + 1926(ActivityThread.java:1926)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 214(Looper.java:214)
       at android.app.ActivityThread.main + 6981(ActivityThread.java:6981)

### BindingFragment

```
abstract class BindingFragment<B : ViewDataBinding> : Fragment() {

  var binding by autoCleared<B>()

  override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
    binding = DataBindingUtil.inflate(
        inflater,
        getLayoutId(),
        container,
        false
    )
    return binding.root
  }

  override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
    super.onViewCreated(view, savedInstanceState)
    binding.lifecycleOwner = viewLifecycleOwner
  }

  @LayoutRes abstract fun getLayoutId(): Int

}
```

**Comment by minhthuanht** [comment]
Hi @azizbekian, 
I'm also having the same error, have you found a solution yet? If you have dealt with it, can you give me some advice? Thanks
Logcat: 
Fatal Exception: java.lang.IllegalStateException
should never call auto-cleared-value get when it might not be available
