### ISSUE TITLE
TypeCastException in NavigationExtensions.kt

### ISSUE THREAD

**Issue by sanisloandras** [googlesamples/android-architecture-components#693]
Hello

I am working on a hobby app, using bottom navigation bar.
I copied the NavigationExtensions.kt extension file from the NavigationAdvancedSample and I get this exception:

`kotlin.TypeCastException: null cannot be cast to non-null type androidx.navigation.fragment.NavHostFragment
        at com.sanislo.soft.photospot.NavigationExtensionsKt$setupItemReselected$1.onNavigationItemReselected(NavigationExtensions.kt:187)
        at com.google.android.material.bottomnavigation.BottomNavigationView$1.onMenuItemSelected(BottomNavigationView.java:201)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
        at com.google.android.material.bottomnavigation.BottomNavigationMenuView$1.onClick(BottomNavigationMenuView.java:115)
        at android.view.View.performClick(View.java:7352)
        at android.view.View.performClickInternal(View.java:7318)
        at android.view.View.access$3200(View.java:846)
        at android.view.View$PerformClick.run(View.java:27800)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7037)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)`

**Comment by sanisloandras** [comment]
So I figured out that the reason why I was getting this exception because the navigation graphs id in the xml should match the id of the menu items in the bottom navigation menu xml.

I think there should be a red huge warning about this restriction, because I have lost like 5 hours of my life debugging this error...

**Comment by cgathergood** [comment]
Hey @sanisloandras thanks for posting this issue. I also spent a couple of hours figuring out why I couldn't replicate this sample. Appreciate it!

**Comment by VyacheslavMartynenko** [comment]
@sanisloandras thanks you. It is really annoying bug.

**Comment by jeremiahlachica** [comment]
@sanisloandras that worked for me too. thank you :)

**Comment by aungtuntun** [comment]
Thanks @sanisloandras , you save my hours. 👍  :)

**Comment by tidoemanuele** [comment]
@sanisloandras you save my day

**Comment by BhargavSavasani** [comment]
kotlin.TypeCastException: null cannot be cast to non-null type androidx.navigation.fragment.NavHostFragment

Getting The Same Issue 
Please Answer Me 
Still waiting...

**Comment by vuthanhict** [comment]
@sanisloandras 
Thank you so much, you save my hours.

**Comment by ajayjg** [comment]
This worked for me too. Thank you very much.

**Comment by abalta** [comment]
@sanisloandras thank you, you save my time.

**Comment by therajanmaurya** [comment]
> So I figured out that the reason why I was getting this exception because the navigation graphs id in the xml should match the id of the menu items in the bottom navigation menu xml.
> 
> I think there should be a red huge warning about this restriction, because I have lost like 5 hours of my life debugging this error...

@sanisloandras Big thanks. Your 5-hour hard work saved me 5 hours 🙂.

**Comment by DanielMarantz** [comment]
Definitely wasted 2 hours of my life on this... thanks @sasanisloandras for saving the other 3 hours. By the way, how did you come to this solution?

**Comment by sanisloandras** [comment]
@DanielMarantz 
I created a separate test project from scratch, just to see what did I do wrong, and that's how I noticed the mistake.

**Comment by franquicidad** [comment]
Hello, I have the same error but the ids do match.
![Screen Shot 2020-12-17 at 3 50 39 PM](https://user-images.githubusercontent.com/28768991/102542648-1b1fea00-4080-11eb-9120-8403be5d16bf.png)

what do i do herE?

**Comment by fvaladares** [comment]
I had a similar problem, after several hours a discover that I forget to pass the layout as the activity parameter:
`AppCompatActivity(R.layout.activity_main) `

**Comment by khmaies5** [comment]
> I had a similar problem, after several hours a discover that I forget to pass the layout as the activity parameter: `AppCompatActivity(R.layout.activity_main) `

this was my error too
