### ISSUE TITLE
[Question] How to cancel data loading?

### ISSUE THREAD

**Issue by wafer-li** [googlesamples/android-architecture-components#9]
There is always the case: the user could not torrent the slow data loading process, and want to cancel it.

But in the sample project, I cannot find there is any method to meet that demand.

So, is there any way to achieve that goal?

> The `cancel data loading` means: 
> When the user perform the cancel action, such as `onBackPressed`, the `NetworkBoundResource` need to cancel the ongoing db loading transaction and the network request

**Comment by wafer-li** [comment]
I also found that the app will crash with the following steps:

1. Type anything to search repos
2. Press the back button several times to quit the app while loading the data
3. Reopen the app and search another word

Logs:

```
E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
Process: com.android.example.github, PID: 15288
java.lang.reflect.UndeclaredThrowableException
  at $Proxy0.intercept(Unknown Source)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
  at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
  at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
  at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.reflect.InvocationTargetException
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.tools.profiler.support.network.OkHttpInterceptorHandler.invoke(OkHttpInterceptorHandler.java:36)
  at java.lang.reflect.Proxy.invoke(Proxy.java:393)
  at $Proxy0.intercept(Unknown Source) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
  at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179) 
  at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129) 
  at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
  at java.lang.Thread.run(Thread.java:818) 
Caused by: java.io.IOException: unexpected end of stream on Connection{api.github.com:443, proxy=DIRECT@ hostAddress=api.github.com/192.30.255.116:443 cipherSuite=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 protocol=http/1.1}
  at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:205)
  at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:67)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  at java.lang.reflect.Method.invoke(Native Method) 
  at com.android.tools.profiler.support.network.OkHttpInterceptorHandler.invoke(OkHttpInterceptorHandler.java:36) 
  at java.lang.reflect.Proxy.invoke(Proxy.java:393) 
  at $Proxy0.intercept(Unknown Source) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
  at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179) 
  at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129) 
  at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
  at java.lang.Thread.run(Thread.java:818) 
Caused by: java.io.EOFException: \n not found: size=0 content=…
  at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:215)
  at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
  at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:67) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
  at java.lang.reflect.Method.invoke(Native Method) 
  at com.android.tools.profiler.support.network.OkHttpInterceptorHandler.invoke(OkHttpInterceptorHandler.java:36) 
  at java.lang.reflect.Proxy.invoke(Proxy.java:393) 
  at $Proxy0.intercept(Unknown Source) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
  at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179) 
  at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129) 
  at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
  at java.lang.Thread.run(Thread.java:818) 
```

**Comment by JoseAlcerreca** [comment]
wafer-li: could you please open another bug for the crash and keep this issue about your question?

**Comment by wafer-li** [comment]
@JoseAlcerreca 
I just thought the reason of that bug might relate to the limitation(cannot cancel data-loading).

I will do it right away

**Comment by codeparams** [comment]
I made a sample app that includes canceling (also my 1st github project). Check it out: [github](https://github.com/codeparams/jetpack_example1) and [blog](https://codeparams.com/jetpack_example1/). It's similar to _github browser sample_ but doesn't use NetworkBoundResource and LiveDataCallAdapterFactory.
